# Site
title:              Qusai Alothman
bio:                'Mathematician. Programmer. And in-between.'
description:        "Data Scientist, Sofware Engineer, and something else."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://max10541.ml

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..3
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed


# Analytics
clicky: 101233497


email:		          alothman.qusai@gmail.com
#github-url:         username
stackoverflow:      9094710/qusai-alothman
linkedin:           qusai-alothman

# Gems
plugins:
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
